language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer install

script:
  - vendor/bin/phpunit -c phpunit.xml.dist
  - vendor/bin/phpstan analyse -l 7 src tests
  - vendor/bin/php-cs-fixer fix --dry-run --diff